// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjymx6-9qME7HLj01xEwRvHUq5DlGOZg',
    appId: '1:842613444516:web:edcd1f6241d5162ec13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    authDomain: 'fir-flutter-codelab-5c300.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JueRXbjQ1Rs2AXfOqEs6TKtqnlN3F6I',
    appId: '1:842613444516:android:34f1bb82a7acb0c6c13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGcF2F8hbIfv3JW5B6M6wChlCVL3bUwI',
    appId: '1:842613444516:ios:81a289297257017ac13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGcF2F8hbIfv3JW5B6M6wChlCVL3bUwI',
    appId: '1:842613444516:ios:81a289297257017ac13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
    iosBundleId: 'com.example.start',
  );

}