// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JueRXbjQ1Rs2AXfOqEs6TKtqnlN3F6I',
    appId: '1:842613444516:android:6ad9f835de2f6a1fc13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGcF2F8hbIfv3JW5B6M6wChlCVL3bUwI',
    appId: '1:842613444516:ios:b339160c079bbe77c13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGcF2F8hbIfv3JW5B6M6wChlCVL3bUwI',
    appId: '1:842613444516:ios:b339160c079bbe77c13b31',
    messagingSenderId: '842613444516',
    projectId: 'fir-flutter-codelab-5c300',
    storageBucket: 'fir-flutter-codelab-5c300.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}